name: 'Test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test: # make sure build/ci work properly
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
         os: [windows-latest, ubuntu-latest]
    steps:
      - name: Get the sources      
        uses: actions/checkout@v2
      - name: Create a release draft for a version tag
        id: create-release-draft       
        uses: ./
        with:
         repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: print the url of the release draft
        run: echo ${{ steps.create-release-draft.outputs.release-url }}
        
